version: '3.8'

services:
  cipheria:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  #dev service
  #cipheria-dev:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.dev
  #    target: dev
  #  ports:
  #    - "3000:3000"
  #  volumes:
  #    - .:/app
  #    - /app/node_modules
  #  environment:
  #    - NODE_ENV=development
  #  profiles:
  #    - dev